homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

webworkshopdod/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home.html')

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Website ini dibuat dalam rangka Latihan Workshop Coding Website DOD 2021.">
        <meta name="keyword" content="Workshop Coding Website DOD 2021">
        <meta name="author" content="Raihan Rizqi">
        <title>Workshop Coding Website DOD 2021</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="icon" href="{% static 'user.png' %}" type="image/x-icon">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark sticky-top">
            <a class="navbar-brand" href="{% url 'homepage:index' %}">Website</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">DROPDOWN</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Dropdown Menu 1</a>
                            <a class="dropdown-item" href="#">Dropdown Menu 2</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">BUKAN DROPDOWN</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Halo pengguna!</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="d-flex justify-content-center align-self-center">
            <div class="container m-5 p-5" style="background: rgba(218, 221, 252, .75); border-radius: 10px">
                <h2 style="text-align: center;">Okaeri!</h2>
                <h3 style="text-align: center;">Selamat datang kembali di home sweet home. Mau ke ruangan manakah kamu?</h3>
                <div class="row justify-content-sm-around">
                    <a href="#" class="btn btn-primary">Ruang Baca</a>
                    <a href="#" class="btn btn-primary">Ruang Kerja</a>
                    <a href="#" class="btn btn-primary">Ruang Tidur</a>
                </div>
            </div>
        </div>        
        <footer class="page-footer mt-auto font-small pl-1">
            <div class="footer-copyright text-center py-2">© Raihan Rizqi Muhtadiin 2021</div>
        </footer>
    </body>
</html>